### ISSUE TITLE
Time series add-on installation fails

### ISSUE THREAD

**Issue by kielhauser** [biolab/orange3-timeseries#1]
(transferred from biolab/orange3)
##### Orange version

3.3.6 (git revision ee294bc) on OSX 10.11 and Windows 10
##### Expected behaviour

The time series add-on should install without problems via the Options -> Add-on -> Orange3-Timeseries -> Install
##### Actual behaviour

An error is given (see attached files) both on Windows and OSX
##### Steps to reproduce the behavior

(see expected behaviour)
##### Additional info (worksheets, data, screenshots, ...)

[Orange3-Timeseries_Error_Msg_Win_10.txt](https://github.com/biolab/orange3/files/363533/Orange3-Timeseries_Error_Msg_Win_10.txt)

[Orange3-Timeseries_Error_Msg_OSX_11.11.txt](https://github.com/biolab/orange3/files/363535/Orange3-Timeseries_Error_Msg_OSX_11.11.txt)

**Comment by kernc** [comment]
The solution on Windows is to install [numpy](http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy), [scipy](http://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy), and [statsmodels](http://www.lfd.uci.edu/~gohlke/pythonlibs/#statsmodels) from prebuilt packages by Cristoph Gohlke (ensure the architecture and Python version match). E.g.
```bash
pip install numpy-1.11.1+mkl-cp34-cp34m-win32.whl \
            scipy-0.17.1-cp34-cp34m-win32.whl \
            statsmodels-0.6.1-cp34-none-win32.whl
```
where pip is the correct pip from the virtual environment where Orange is installed. Then, the add-on should install on Windows. Unfortunately, I don't see an easy way around on Windows.

**Comment by kielhauser** [comment]
Thanks for the windows solution - for OSX i found a workaround after some trial and error: removing the binary version of orange and reinstalling it from source using python3 / pip3  (using python/pip doesn't work though)

**Comment by kernc** [comment]
On OS X, the statsmodels project provides prebuilt wheel packages for OS X. Unfortunately, they weirdly only conditionally include pandas package in the install requirements, which makes the package not installable since the pandas dependency, which should be a hard dependency, obviously, is not satisfied.
The solution is to `pip install pandas` before installing the add-on on OS X (with the correct pip). This may be saved altogether with the most recent version of statsmodels (==0.8.0, for which wheels are not available).

Yes, Orange3-Timeseries as well as Orange in whole requires Python 3. Thanks.

**Comment by ajdapretnar** [comment]
Could we somehow check the OS and perhaps remove Timeseries from the list? At least until we (hopefully) move to Anaconda?

**Comment by lmnoeme** [comment]
Hi, I know this is an ongoing issue, but do you think there is any chance the timeseries add-on installation can work any time soon?
I'm afraid I have no idea how to install it through Anaconda or whatever.

**Comment by kernc** [comment]
It should work if you:
1. Download and install [Orange (Standalone Miniconda installer)](https://orange.biolab.si/download/windows/).
2. Go to menu Options > Settings, tab Add-ons, check "Install add-ons with conda".
3. Go to menu Options > Add-ons and install Timeseries add-on, successfully.

**Comment by lmnoeme** [comment]
Thanks for your response.
That's what I did and it failed.
Same error message as decribed at https://github.com/biolab/orange3/issues/1691

**Comment by kernc** [comment]
Did you do the 2. step above? The check is not there by default.

**Comment by lmnoeme** [comment]
Thanks for pointing that out to me.
I had skipped step 2 the first time.
I have done it this time but it still doesn(t work.
The error message is still the same.

**Comment by lmnoeme** [comment]
I'm using 64-bit Windows.
Can the problem stem from that?

**Comment by lmnoeme** [comment]
All right, I have uninstalled Orange, then installed Anaconda and reinstalled Orange from the Anaconda navigator.
It's working now.
Thanks for your support.

**Comment by lmnoeme** [comment]
I've just realized that Anaconda does not  feature the latest version of Orange.
It currently has version 3.4.1
Do you know if there is a way to get the latest version under Anaconda?

**Comment by astaric** [comment]
You need to add the conda-forge channel.

https://orange.biolab.si/download/#anaconda

**Comment by processo** [comment]
Might be useful for those on Windows without any conda (Orange 3.11.0):
1) Install Microsoft Windows SDK 7.1 (www.microsoft.com/download/details.aspx?id=8279)
2) If setup failes with ``PermissionError: [WinError 5] Access is denied: 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-o29stj1u-uninstall\\program files\\orange\\lib\\site-packages\\scipy\\integrate\\lsoda.pyd'`` run Orange as admin during setup (right click -> Run as administrator).

**Comment by ajdapretnar** [comment]
Solution is as suggested by @astaric.
