### ISSUE TITLE
Orange Timeseries Error Opening Line Chart Widget

### ISSUE THREAD

**Issue by Garch2017** [biolab/orange3-timeseries#10]
Hi,

Could anyone assist with the Orange Timeseries Chart Widget Error below? When I double-click on the widget the error pop up as below.

Many thanks.

-------------------------- AttributeError Exception ---------------------------
Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/orangecontrib/timeseries/widgets/owlinechart.py", line 66, in enterEvent
    self.button_close.setVisible(True)
AttributeError: 'PlotConfigWidget' object has no attribute 'button_close'
-------------------------------------------------------------------------------

![screen shot 2017-03-03 at 13 29 45](https://cloud.githubusercontent.com/assets/26165547/23552570/864706f2-0014-11e7-85c3-3ede5b9d0fd2.png)

**Comment by kernc** [comment]
If you're willing to install from git, e.g.
```py
pip3 install -U https://github.com/biolab/orange3-timeseries/archive/master.zip
```
(with pip3 of your environment where Orange is installed), it may have been [solved yesterday](https://github.com/biolab/orange3-timeseries/issues/9) along with [a similar issue](https://github.com/biolab/orange3-timeseries/issues/8).

**Comment by Garch2017** [comment]
Kernc, thanks for you suggestion. I tried as you suggested and it installed just fine. But I still the error below when I double-click on LineChart.


Exception:
AttributeError: 'PlotConfigWidget' object has no attribute 'button_close'
Module:
orangecontrib.timeseries.widgets.owlinechart:66
Widget Scheme:
/var/folders/15/tk8pzynd05bd88hpmb15824c0000gr/T/ows-0uc8dkvs.ows.xml
Version:
3.3.12
Environment:
Python 3.4.2 on Darwin 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
Installed Packages:
AnyQt==0.0.8, Bottleneck==1.2.0, LTTL==2.0.1, Orange3-DataFusion==0.1.10, Orange3-Recommendation==0.1.3, Orange3-Text==0.2.3, Orange3-Textable==3.0b0, Orange3-Timeseries==0.2.6, Orange3==3.3.12, beautifulsoup4==4.5.3, boto==2.46.1, bz2file==0.98, chardet==2.3.0, decorator==4.0.11, dill==0.2.6, docutils==0.13.1, future==0.16.0, gensim==1.0.0, gnureadline==6.3.3, ipython==3.0.0, joblib==0.10.3, keyring==10.2, keyrings.alt==2.0, mock==2.0.0, networkx==1.11, nltk==3.2.2, numpy==1.10.4, oauthlib==2.0.1, pandas==0.19.2, patsy==0.4.1, pbr==2.0.0, pip==8.1.2, psycopg2==2.6, pyqtgraph==0.10.0, python-dateutil==2.6.0, pytz==2016.10, qt-graph-helpers==0.1.3, requests-oauthlib==0.8.0, requests==2.13.0, scikit-fusion==0.2.1, scikit-learn==0.18.1, scipy==0.18.1, setuptools-git==1.2, setuptools==18.8.1, simhash==1.7.1, six==1.10.0, smart-open==1.4.0, statsmodels==0.8.0, tweepy==3.5.0, validate-email==1.3, wikipedia==1.4.0, xlrd==1.0.0
Machine ID:
27141537854380
Stack Trace:
Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/orangecontrib/timeseries/widgets/owlinechart.py", line 66, in enterEvent
    self.button_close.setVisible(True)
AttributeError: 'PlotConfigWidget' object has no attribute 'button_close'

Local Variables:
{'event': <PyQt4.QtCore.QEvent object at 0x12beb85e8>,
 'self': <orangecontrib.timeseries.widgets.owlinechart.PlotConfigWidget object at 0x12b2541f8>}

Install Log:
![screen shot 2017-03-03 at 14 08 51](https://cloud.githubusercontent.com/assets/26165547/23553635/9e67930a-0019-11e7-88c4-b7c1de9e1330.png)

**Comment by Harmony89** [comment]
Hi I also have the same problem as Garch2017. Yesterday I installed the latest version of Orange Canvas then after that I installed Numpy, Scipy and Statsmodels. After that I installed Time series plugin and when I want to use Line chart widget the same error appears (AttributeError: 'PlotConfigWidget' object has no attribute 'button_close'...). Please help!

**Comment by kernc** [comment]
@Garch2017 you were updating Orange3-Timeseries in the wrong Python environment. See on the screenshot how you pip-installed it in _./anaconda/lib/python3.6/site-packages_ whereas Orange errored in _/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/orangecontrib/timeseries/widgets/owlinechart.py_. Different versions of Python.

Right. I released [0.2.7](https://github.com/biolab/orange3-timeseries/releases/tag/0.2.7) on PyPI which should be available to download through Orange Canvas add-ons dialog tomorrow (or as soon as PyPI updates). Please try again with the update.

**Comment by Harmony89** [comment]
Thank you for your reply. Works like a charm ;)

**Comment by Garch2017** [comment]
kernc, many thanks.
