### ISSUE TITLE
Line Chart does not have context settings

### ISSUE THREAD

**Issue by janezd** [biolab/orange3-timeseries#108]
See https://github.com/biolab/orange3/issues/4697.

Line Chart has only a setting `attrs`, which is not even used in the widget.

The widget is written using javascript and highcharts. It probably has to be rewritten from scratch.

**Comment by ajdapretnar** [comment]
Uh, actually, it looks like there are several issues related to Line Chart.
#109 for missing confidence plot
#111 for context settings
#58 for replacing Highcharts altogether

At least for Line Chart it would be a nice summer project for someone to rewrite it to Qt if possible.

**Comment by janezd** [comment]
No (longer?) true.
