### ISSUE TITLE
Line Chart: crashes when var name changed

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-timeseries#111]
##### Timeseries version

0.3.6

##### Orange version

3.26.0.dev

##### Expected behavior
Line Chart updates variable list and keeps the selection when changing variable name.

##### Actual behavior
Line Chart crashes.

##### Steps to reproduce the behavior
Yahoo Finance - Edit Domain - Line Chart. Select a variable to show.
Change variable name in Edit Domain. Re-select the renamed variable.

##### Additional info (worksheets, data, screenshots, ...)
```
---------------------------- ValueError Exception -----------------------------
Traceback (most recent call last):
  File "/Users/ajda/orange/orange3-timeseries/orangecontrib/timeseries/widgets/owlinechart.py", line 171, in setSeries
    newseries.append(data.get_column_view(attr)[0])
  File "/Users/ajda/orange/orange3/Orange/data/table.py", line 1109, in get_column_view
    col_index = self.domain.index(index)
  File "/Users/ajda/orange/orange3/Orange/data/domain.py", line 356, in index
    raise ValueError("'%s' is not in domain" % var)
ValueError: 'New name' is not in domain
-------------------------------------------------------------------------------
```

**Comment by PrimozGodec** [comment]
I believe it is fixed already
