### ISSUE TITLE
TimeSlice is blank when import CSV

### ISSUE THREAD

**Issue by DoctorDib** [biolab/orange3-timeseries#115]
##### Timeseries version
0.3.6

##### Orange version
3.25.0

##### Expected behavior
I was expecting to view my data in a data table while being able to select a date and time, however the TimeSlice is blank as if there is no data. 

##### Actual behavior
![image](https://user-images.githubusercontent.com/14931616/84638375-d065bf80-aeee-11ea-81dd-ae2a9f3ced16.png)
Just a blank TimeSlice which means blank Data Table, no errors occur in Orange, I am tried it with another dataset of mine (with the same datetime string format) and it still fails.

##### Steps to reproduce the behavior
Import a CSV, add a time slice and add a Data Table. (maybe have the same datetime string format)

My structure:
![image](https://user-images.githubusercontent.com/14931616/84638243-9c8a9a00-aeee-11ea-9b2a-0c84556b8ca2.png)

##### Additional info (worksheets, data, screenshots, ...)
This is the format of my datetime string:
![image](https://user-images.githubusercontent.com/14931616/84638639-2aff1b80-aeef-11ea-935e-18040c040c30.png)

**Comment by kernc** [comment]
Attaching simple, minimal data for reproduction often expedites bug triage.

**Comment by Xelaroom** [comment]
Hello

have the same problem

System win 10 / 1903
Orange 3.26
TimeSeries 0.3.6

Time Slice apparently has problems.

See example.


[example.zip](https://github.com/biolab/orange3-timeseries/files/4836358/example.zip)

**Comment by ajdapretnar** [comment]
@Xelaroom The second issue is already resolved, probably with #117.
The first one remains, I opened another issue for it, since it is a specific problem.
