### ISSUE TITLE
Line Chart: error when saving image as .svg

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-timeseries#130]
##### Timeseries version

0.3.7

##### Orange version

3.27.dev

##### Expected behavior
Line Chart saves .svg files.

##### Actual behavior
Svg files from Line Chart are corrupted.

##### Steps to reproduce the behavior
Save a plot as .svg.

**Comment by janezd** [comment]
This is a highchart widget, so fixing this should be a waste of time since we will eventually migrate from highcharts anyway.

In other words, will be fixed in #58.
