### ISSUE TITLE
 UnicodeDecodeError: 'gbk' codec can't decode byte 0x99 in position 834: illegal multibyte sequence

### ISSUE THREAD

**Issue by ouening** [biolab/orange3-timeseries#135]
##### Timeseries version

Timeseries version: 0.3.7

##### Orange version

Orange version: 3.27

##### Expected behavior
Install Timeseries sucessuffly.

##### Actual behavior
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\temp\Temp\pip-install-isde1r60\orange3-timeseries\setup.py", line 9, in <module>
        LONG_DESCRIPTION = open(README_FILE).read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x99 in position 834: illegal multibyte sequence

##### Additional info (worksheets, data, screenshots, ...)
I solved it by manually modified `setup.py` file in **line 4**:
`LONG_DESCRIPTION = open(README_FILE,encoding='utf-8').read()`

**Comment by ajdapretnar** [comment]
Would you mind making a pull request if you have managed to solve the issue?

**Comment by ouening** [comment]
Sorry, I don't know how to make a pull request, so I create an issue here.

**Comment by ajdapretnar** [comment]
No need to close the issue, especially if the problem hasn't been solved. Creating a PR is quite simple. You can read about it here: https://opensource.com/article/19/7/create-pull-request-github. This is a nice way for you to have a contribution in an open source community, so I would encourage you to try. If you don't want to, just let me know and I will submit the fix.

**Comment by ajdapretnar** [comment]
@ouening Would you be able to confirm this works?

[orange3-timeseries-unicode-error.zip](https://github.com/biolab/orange3-timeseries/files/5429519/orange3-timeseries-unicode-error.zip)

Drag and drop the zip to the Add-on dialogue and run it. It should install normally. Please confirm, so that we can accept the fix.
