### ISSUE TITLE
Interpolation does not consider the time-variable

### ISSUE THREAD

**Issue by WolfgangK1MET** [biolab/orange3-timeseries#136]
##### Timeseries version

0.3.7

##### Orange version

3.xx

##### Expected behavior
I would expect interpolation to take the time-distance from data-entries into account.
For the given example, this would mean that the interpolated values would be 16, 18, 20.

##### Actual behavior
Interpolation is independent on the timevariable distance.
This results in wrong interpolation values for irregular timed entries.

##### Steps to reproduce the behavior
Use the provided Dataset and Interpolation widget.

##### Additional info (worksheets, data, screenshots, ...)
![data](https://user-images.githubusercontent.com/61154310/96251865-5f740880-0fb1-11eb-8319-0800087eef35.png)
![interp_sp](https://user-images.githubusercontent.com/61154310/96251884-6569e980-0fb1-11eb-8fe8-9416204a50f3.png)

**Comment by kernc** [comment]
This seems the offending linear _x_ axis:
https://github.com/biolab/orange3-timeseries/blob/f4f7934f6cc55774342cce46ad2f1fef7c692cfd/orangecontrib/timeseries/functions.py#L274
It should instead probably be `Timeseries(data).time_values`:
https://github.com/biolab/orange3-timeseries/blob/f4f7934f6cc55774342cce46ad2f1fef7c692cfd/orangecontrib/timeseries/timeseries.py#L201-L207

Care to make a PR for it?

**Comment by WolfgangK1MET** [comment]
Hi,
thanks, that is exactly the issue.
I will work on the fix and make a PR in the next days, currently busy with a lot of other stuff.
