### ISSUE TITLE
Data from cursor does not match

### ISSUE THREAD

**Issue by hufnala** [biolab/orange3-timeseries#138]
##### Timeseries version
 newest, PC is off at the moment

##### Orange version

3.27

##### Expected behavior
A Cursor line on more than 1 Plots show data from the same dataset independing of zoom

##### Actual behavior
Shown values are not from the same dataset if there is a lot of data.

##### Steps to reproduce the behavior
Load a dataset with more than 5000 entries and a couple of data columns, in my set i use numeric values with 3 digits, there's some spikes in the dataset, add at least 3..4 plots, activate cursor on one value, >data shown in text window does not fit on all plots (known & checked results). Zooming the plot changes the behavior on unknown zoomlevel, data matches, zoom out again - data does not march any more again.

**Comment by kernc** [comment]
This is a [Highcharts feature](https://www.highcharts.com/docs/stock/data-grouping):
> Grouping is activated when there are many data points in the chart. As well as increasing performance, it makes it easier to spot trends in a chart. By default, the grouping approximation depends on the type of series: Line type series use an _average_ approximation.

Strongly leaning to wontfix.

**Comment by ajdapretnar** [comment]
I see your point, but if this is indeed a Highcharts feature, bypassing it here would be difficult (also considering we stay away from JS as much as possible). I suspect could be fixed eventually with #58.

I think for now, it would have to be a wontfix. I suggest using Time Slice for creating subsets.
