### ISSUE TITLE
color problem with Time Series Add-on

### ISSUE THREAD

**Issue by RodrigoCns** [biolab/orange3-timeseries#139]
##### Timeseries version

0.3.7

##### Orange version

3.26.0

##### Expected behavior
When changing lines of various plots in the Line Plot Widget, the colors should follow a order (blue, red, green, etc.)

##### Actual behavior
When changing lines of various plots in the Line Plot Widget, the colors actually keep progressing through the color sequence, as if the changed line was a different one.

##### Steps to reproduce the behavior
From a temporal data table with a couple of columns (A,B,C,D,E,F)
Add 2 or more plots to a Line Chart Widget. 
Select the data of each one (A B in first plot, C D in second plot).
Change one of the lines some times (D to E, to F, to D again, to A, to D, etc).
Each change makes the color keep changing, with the same number of lines.

Bonus: if I change the data table to a diferent one with similar data (Aa, Ba, Ca, Da, Ea, Fa), all lines get new colors, and now it is much harder to see the data. 

##### Additional info (worksheets, data, screenshots, ...)
1st: all fine. 2nd: changing line color. 3rd: changed sheet, color hell.
https://drive.google.com/file/d/1fcl0pdcUh_yOEnofQKOwgskElHdFX5_u/view?usp=sharing
https://drive.google.com/file/d/1JBI6wqVqrhJRebYhH0prXOyX9sdS5nTH/view?usp=sharing
https://drive.google.com/file/d/1VxBwHrsF6VT6TiIpRhRxbBlMQ6UoeWoF/view?usp=sharing

**Comment by kernc** [comment]
The solution might be to set a fixed line `color` here:
https://github.com/biolab/orange3-timeseries/blob/f4f7934f6cc55774342cce46ad2f1fef7c692cfd/orangecontrib/timeseries/widgets/owlinechart.py#L246-L250

**Comment by janezd** [comment]
This will also be fixed as a part of #56.
