### ISSUE TITLE
Yahoo Finance widget fails to download the data

### ISSUE THREAD

**Issue by ghoseiri** [biolab/orange3-timeseries#14]
Hi, Yahoo Finance widget fails to download the data no matter what the symbol or date you pick: " failed to download data (HTTP Error -1). Wrong ..."

**Comment by ajdapretnar** [comment]
Yup, same here. The widget should either be fixed to work or removed if not possible to fix.

**Comment by jerneju** [comment]
Yahoo API has not been working since early this year.

**Comment by ajdapretnar** [comment]
So we should remove the widget. We can always bring it back in case the API magically returns to life.

**Comment by jerneju** [comment]
This widget needs upgrading and renaming. See: https://www.quandl.com/tools/python
