### ISSUE TITLE
Datasets link is broken

### ISSUE THREAD

**Issue by lanzagar** [biolab/orange3-timeseries#15]
When installing the addon through Orange, a link is created in my Orange/datasets dir pointing to /tmp/pip-build-1xqxeaa8/Orange3-Timeseries/orangecontrib/timeseries/datasets
I am not sure I would like this add-on creating a link somewhere on my computer in any case (even if the link would actually point to something that exists).

**Comment by ajdapretnar** [comment]
Closed due to inactivity.
