### ISSUE TITLE
Widget UI changes following new orange-widget-base release

### ISSUE THREAD

**Issue by irgolic** [biolab/orange3-timeseries#152]
Following the merge and release of https://github.com/biolab/orange-widget-base/pull/130, widgets will look a bit different. All widgets should be checked and adjusted.

See https://github.com/biolab/orange-widget-base/wiki/Widget-UI

**Comment by janezd** [comment]
I checked all widgets and haven't seen anything particularly bad (and caused by the mentioned changes in widget-base).

I'm thus closing this issue, also because I plan to revamp these widgets anyway.
