### ISSUE TITLE
Time Series cannot find QfontDatabase

### ISSUE THREAD

**Issue by zizidzhelil** [biolab/orange3-timeseries#153]
Hi,
I hit the following error: #151 
I see that it is closed 3 days ago but it still does not work.

Is it not released yet?

##### Timeseries version

0.3.9

##### Orange version

3.27.1

##### Expected behavior

I should be able to use it.

##### Actual behavior

QfontDatabase cannot be found

##### Steps to reproduce the behavior

Just install Time Series and try to use it.

##### Additional info (worksheets, data, screenshots, ...)
```
Traceback (most recent call last):
  File "C:\Program Files\Orange\lib\site-packages\orangecanvas\scheme\widgetmanager.py", line 231, in __add_widget_for_node
    w = self.create_widget_for_node(node)
  File "C:\Program Files\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 296, in create_widget_for_node
    widget = self.create_widget_instance(node)
  File "C:\Program Files\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 409, in create_widget_instance
    widget.__init__()
  File "C:\Program Files\Orange\lib\site-packages\orangecontrib\timeseries\widgets\owtimeslice.py", line 243, in __init__
    self.icons_font = load_icons_font()
  File "C:\Program Files\Orange\lib\site-packages\orangecontrib\timeseries\widgets\owtimeslice.py", line 102, in load_icons_font
    font_family = QFontDatabase.applicationFontFamilies(fontId)[0]
IndexError: list index out of range
```

**Comment by zizidzhelil** [comment]
I managed to make to make it work by downloading the source code of the latest release and replacing it in the following location:

```
C:\Program Files\Orange\Lib\site-packages\orangecontrib\
```

The new release contains everything necessary but when I try to download it from the addons of Orange it still does not work.

**Comment by Terrymary222** [comment]
> Hi,
> I hit the following error: #151
> I see that it is closed 3 days ago but it still does not work.
> 
> Is it not released yet?
> 
> ##### Timeseries version
> 0.3.9
> 
> ##### Orange version
> 3.27.1
> 
> ##### Expected behavior
> I should be able to use it.
> 
> ##### Actual behavior
> QfontDatabase cannot be found
> 
> ##### Steps to reproduce the behavior
> Just install Time Series and try to use it.
> 
> ##### Additional info (worksheets, data, screenshots, ...)
> ```
> Traceback (most recent call last):
>   File "C:\Program Files\Orange\lib\site-packages\orangecanvas\scheme\widgetmanager.py", line 231, in __add_widget_for_node
>     w = self.create_widget_for_node(node)
>   File "C:\Program Files\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 296, in create_widget_for_node
>     widget = self.create_widget_instance(node)
>   File "C:\Program Files\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 409, in create_widget_instance
>     widget.__init__()
>   File "C:\Program Files\Orange\lib\site-packages\orangecontrib\timeseries\widgets\owtimeslice.py", line 243, in __init__
>     self.icons_font = load_icons_font()
>   File "C:\Program Files\Orange\lib\site-packages\orangecontrib\timeseries\widgets\owtimeslice.py", line 102, in load_icons_font
>     font_family = QFontDatabase.applicationFontFamilies(fontId)[0]
> IndexError: list index out of range
> ```

same as mine.
time slice can not work in New versrion too.
