### ISSUE TITLE
Line chart not working for an specific dataset

### ISSUE THREAD

**Issue by neliebi** [biolab/orange3-timeseries#160]
##### Timeseries version

0.3.10

##### Orange version

3.28.0

##### Expected behavior
Display the line charts

##### Actual behavior
Features are not shown in the line chart. The module works fine for most of my datasets, but for some reason it's failing when I try to load this specific dataset.

##### Steps to reproduce the behavior
Just add the line chart module using the dataset below.

##### Additional info (worksheets, data, screenshots, ...)
[https://ibb.co/W6QQ1d9](url)

> i,Test no_filter w1,Test no_filter w2,MM filter w1,MM filter w2
1,1.2416,1.233,44.364,43.5273
2,2.3043,2.3245,170.4854,170.858
3,4.6013,5.2083,476.332,560.6115
4,3.7617,5.8212,366.9052,657.641
5,3.0978,4.8875,281.1096,520.6104
6,2.5749,4.1079,220.3818,423.2661
7,2.2543,3.514,178.4243,345.0648
8,1.9723,3.0328,142.7602,280.1494
9,1.7967,2.6674,120.2743,230.6973
10,1.6664,2.4066,101.4004,194.2702
11,1.4702,2.0667,74.6831,148.8543
12,1.4482,1.8223,68.9377,115.6784
13,1.3436,1.6504,55.7334,90.3337
14,1.3338,1.5315,51.8248,69.7425
15,1.5481,1.7656,74.1751,89.1125
16,1.94,2.3837,123.2566,164.5248
17,2.4473,3.1742,192.3158,271.4973
18,3.0689,4.0314,275.2885,395.6504
19,3.3216,4.6485,315.7318,483.984
20,3.2813,4.7688,309.9266,514.0282
21,2.8568,4.3903,248.3381,465.0104
22,2.2933,3.6818,176.6831,356.2948
23,2.0309,3.0788,142.2681,271.2065
24,1.7716,2.6634,108.8053,215.8396
25,1.737,2.4265,102.8566,181.6477
26,1.563,2.2409,82.12,157.0023
27,1.4539,1.9536,70.9119,125.5118
28,1.4401,1.8169,68.591,111.5406
29,1.3685,1.6656,59.6082,95.0453
30,1.3195,1.5434,55.5282,81.1139
31,1.3124,1.4809,52.797,73.3663
32,1.2955,1.4568,51.1614,68.9317
33,1.2819,1.4261,49.4919,66.1566
34,1.2706,1.3811,47.6591,59.6023
35,1.2869,1.3563,49.5537,57.8471
36,1.2711,1.3294,47.438,53.4544
37,1.2627,1.3082,46.8782,52.6794

*Some times I get this error message when I try to load this dataset
https://ibb.co/0Bp8KXL

**Comment by neliebi** [comment]
I found that when I load the line chart, the dictionary context.attributes in the method match(self, context, _, attrs, metas) in owlinechart.py (line 428) contains elements from another data set (that is not even loaded in the current project)

**Comment by neliebi** [comment]
I was able to make it work after clicking in "Options->Reset widget settings"

**Comment by ajdapretnar** [comment]
Seems like context settings are off. @janezd ?

**Comment by PrimozGodec** [comment]
It is probably my fault. :( will try to take a look ASAP

**Comment by wvdvegte** [comment]
I've seen this same behavior with a dataset I'm currently working with, including the error message. Sometimes it works fine, sometimes the features aren't shown.

**Comment by PrimozGodec** [comment]
Fixed in https://github.com/biolab/orange3-timeseries/pull/167
