### ISSUE TITLE
Line Chart - No data display

### ISSUE THREAD

**Issue by Milda654** [biolab/orange3-timeseries#161]
- [ ] **What's wrong?**

Hello, I have a problem with visualize a 
time series in widget LineChart. As you can see in the attachment, there are data in datatable, distributions is working as well. I really don't know, where problem is. Thank you for your support. 

![LineChartError](https://user-images.githubusercontent.com/81708239/113190705-edd8ff80-925c-11eb-90e0-eefb64cd9d5b.JPG)

- [ ] **How can we reproduce the problem?** 

I started workflow with loading the .xlsx file, than I continued with widgets as you can see in the file and picture.

[time_series_orange.zip](https://github.com/biolab/orange3/files/6238604/time_series_orange.zip)

- [ ] **What's your environment?**

- Operating system: Windows 10
- Orange version: 3.28.0
- How you installed Orange: 
**Downloaded install file there: https://download.biolab.si/download/files/Orange3-3.28.0-Miniconda-x86_64.exe
Then I used common installator. Miniconda and Orange is installated on disc D:\\**

**Comment by guiom2959** [comment]
Hi I experience quite a few bugs as well with Line Charts,
I was able to see some data once, then once the bug appears, I am unable to see any data again. 
data : 
![Capture d’écran 2021-04-23 à 15 00 49](https://user-images.githubusercontent.com/82681547/115918006-f29c6800-a444-11eb-8f38-81a7a58c4c37.png)
![Capture d’écran 2021-04-23 à 15 00 55](https://user-images.githubusercontent.com/82681547/115918019-f4fec200-a444-11eb-89c1-b4f7692e731c.png)
![Capture d’écran 2021-04-23 à 15 01 21](https://user-images.githubusercontent.com/82681547/115918021-f62fef00-a444-11eb-8215-103089c76ba2.png)

source : 
https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto3/TotalesPorRegion.csv

version  : 
orange 3.27.1 and 3.28 (behavior seems worse on last version)

**Comment by janezd** [comment]
We have problems reproducing this. However, this widget will be reimplemented (probably as the first widget) as a part of #58, so I'm closing this.
