### ISSUE TITLE
Line charts in Orange 3.27 don't work

### ISSUE THREAD

**Issue by aserehal** [biolab/orange3-timeseries#162]
- [ ] **What's wrong?**

Line charts don't display data. Projects that were working fine in 2.23 don't display data in the line chart after I updated to m3.27.
I get a blank canvas with a message: "No data to display"
![image](https://user-images.githubusercontent.com/53316938/107151926-42ce5880-6933-11eb-9bc9-eb38d26acb79.png)

- [ ] **How can we reproduce the problem?** 

I tried many data sets, include Orange data sets

- [ ] **What's your environment?**

- Operating system: 64 bi operating system
- Orange version: 3.27.1
- How you installed Orange: Anaconda

**Comment by ajdapretnar** [comment]
I will assume this was fixed in #220. At least it works for me with the provided data and workflow.
