### ISSUE TITLE
__seq__ column no longer produced as output from As Timeseries widget

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3-timeseries#163]
##### Timeseries version
0.3.10

##### Orange version
3.28

##### Expected behavior
A Timeseries widget produces a column named __seq__ containing the row numbers

##### Actual behavior
A Timeseries widget no longer produces a column named __seq__ containing the row numbers

##### Steps to reproduce the behavior
Provide As Timeseries with input and connect its output to a Data Table. Then check the table: there is no sequence column

##### Additional info (worksheets, data, screenshots, ...)
Sequence column was useful, for instance when using Moving Transform.
If the size of the window of the moving transform is N, I would like to be able to easily exclude the first N instances because these records have less than N predecessors, and may be subject to more fluctuations.

**Comment by ajdapretnar** [comment]
Seq column was removed on purpose, because it offers no additional information - row numbers are visible from the data table. To achieve what you are after, then Moving Transform should perhaps offer this option. The current behaviour actually goes against pandas convention, so we should change it.

**Comment by wvdvegte** [comment]
@ajdapretnar - OK, thanks. Actually that seems like a good idea. I will open another issue for it.
