### ISSUE TITLE
Moving Transform: add option to remove first n instances (n = window size)

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3-timeseries#164]
##### Timeseries version
0.3.10

##### Orange version
3.28

##### Expected behavior
In moving transform with overlapping windows, it should be possible (as an option) to exclude the first n rows from the output, with n the size of the window - after their values have been used to calculate the outputs for rows [n+1 .. 2n]. The first n rows have less than n predecessors, therefore they are calculated differently from rows n+1 onwards. It is currently even not specified how their output values are determined. This should also be made explicit, in case the suggested option is not selected.

##### Actual behavior
I assume the of the first n rows is based on applying the aggregation function to each row itself and its (less than n) predecessors. It might even be that leading zeroes are used - I haven't checked

##### Steps to reproduce the behavior
Apply Moving Transform (overlapping windows) to a time-series dataset and check the output.

**Comment by janezd** [comment]
This should be handled at the same time as fixing #184.
