### ISSUE TITLE
Yahoo Finance / does not appear in Times Series

### ISSUE THREAD

**Issue by Prog-LucasAlves** [biolab/orange3-timeseries#172]
##### Actual behavior
I installed the default orange (my system is: Windows 10 x64) / after installed I added the Time Series add-on wanting to use Yahoo Finance.

But the Yahoo Finance option does not appear in the Time Series add-on options list.
As shown in the image below.

Any tips on what to do to get this option listed?

##### Additional info (worksheets, data, screenshots, ...)
![Captura de tela 2021-07-14 114146](https://user-images.githubusercontent.com/68572723/125651398-0cbfda9f-6c51-46a6-a090-e2b398cf39d0.png)

**Comment by nuhyurduseven** [comment]
I got same issue. Anyone who why or solution?

**Comment by janezd** [comment]
I see nothing in the widget that could cause this. Closing for now, will reopen if it happens again.
