### ISSUE TITLE
Finance Yahoo widget not downloading

### ISSUE THREAD

**Issue by shiuhng** [biolab/orange3-timeseries#174]
![Untitled](https://user-images.githubusercontent.com/42687379/130307137-00b5f593-cc9d-47e3-8ef9-a2c6fe5dfa83.jpg)

**What's wrong?**

Finance yahoo widget not downloading data.
I tried ticker sign of BA, AAPL, 7160.KL all giving error
It used to work, I was using it since Dec 2020, it probably failed around June 2021

Rgds,

**How can we reproduce the problem?** 

**What's your environment?**

- Operating system:
- Orange version:
- How you installed Orange:

**Comment by janezd** [comment]
Yes, the error show be more informative, and should mention the possible problems with the user's connection or Yahoo's API.
