### ISSUE TITLE
Line Chart: bug in visualization

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-timeseries#18]
No visualization when Logarithmic axis ticked, unless 'columns' chosen as a display option. But the user has to re-select columns when ticking the log option to see the visualization.

<img width="1219" alt="screen shot 2017-10-12 at 13 50 05" src="https://user-images.githubusercontent.com/12524972/31494806-3b3fe750-af55-11e7-9f84-ca1f4380f0ed.png">

**Comment by ajdapretnar** [comment]
Another bug. Intervals not symmetric. I have data points spread across the entire year as shown in Distributions.
<img width="846" alt="screen shot 2017-10-24 at 09 35 51" src="https://user-images.githubusercontent.com/12524972/31930158-036ff9b6-b89f-11e7-9bfb-8f457051b0d3.png">

Line Chart, however, decides to emphasis December as if most data points are from that time period. Which they aren't.
<img width="900" alt="screen shot 2017-10-24 at 09 35 40" src="https://user-images.githubusercontent.com/12524972/31930165-07cc7f48-b89f-11e7-9496-fac509794a8a.png">

**Comment by kernc** [comment]
I don't think it shows what you say. Line chart "emphasizes" December because the _highest temperature_ was measured at some time early December.

In either case, don't hijack issues dissimilar in nature. 😛

**Comment by ajdapretnar** [comment]
When I use As Timeseries before Line Chart, it shows correct visualization. I am also not sure _why_ I would want it emphasized like this. I will know when the highest temperature was measures from the peak, not from the time slice length. It just skews the visualization and can easily lead to misinterpretation of results, just like dissimilar x and y axes in Scatter Plot. I think this is very bad.

> In either case, don't hijack issues dissimilar in nature.
I agree. I repent.

**Comment by jerneju** [comment]
@ajdapretnar : Is this still an issue?

**Comment by ajdapretnar** [comment]
Does not happen on current master.
