### ISSUE TITLE
Moving Transform / cumulative sum multiplies outcomes by -1

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3-timeseries#184]
##### Timeseries version
0.3.13

##### Orange version
3.31.1

##### Expected behavior
When applying Cumulative Sum to a column, it should return the sum of each value plus all the previous values in the same column

##### Actual behavior
When applying Cumulative Sum to a column, it returns the sum of each value plus all the previous values in the same column, multiplied by -1

##### Steps to reproduce the behavior
Apply Cumulative Sum to a column in a dataset, set the window size to a number larger than the total number of records, observe the outcomes (see the attached example)

##### Additional info (worksheets, data, screenshots, ...)

[cumsum bug reporting.ows.zip](https://github.com/biolab/orange3-timeseries/files/7977325/cumsum.bug.reporting.ows.zip)

**Comment by janezd** [comment]
I didn't even get that far. 

Whatever I try, I keep getting an error like

```
ValueError: all the input array dimensions for the concatenation axis must match exactly,
but along dimension 0, the array at index 0 has size 15 and the array at index 1 has size 144
```

where 144 is the initial data length and 15 is 144 divided by window width.

**Comment by janezd** [comment]
Implement #164 at the same time.
