### ISSUE TITLE
Years get multiplied by 1000 in Timeseries Line Chart

### ISSUE THREAD

**Issue by kaimikael** [biolab/orange3-timeseries#186]
##### Timeseries version

0.3.12

##### Orange version

3.31.1

##### Expected behavior
I nicked a dataset that had data per year.  I plot the data and expect to get the years along the _x_ axis. 

##### Actual behavior
The years are labelled as “2014k”, “2015k”, etc, as can be seen in this screenshot:
<img width="1037" alt="Screenshot 2022-03-01 at 10 44 47" src="https://user-images.githubusercontent.com/10616212/156145768-c75325a1-abf7-41fe-8619-f69192952981.png">

The manual page indicates this is not intentional behaviour.  The output from As Timeseries looks OK.

##### Steps to reproduce the behavior
I attach a workflow and data, open the Line Chart to see the labelling.
[AI.publications.by.year.past.decade.csv](https://github.com/biolab/orange3-timeseries/files/8160599/AI.publications.by.year.past.decade.csv)
[YearsInLineChart.zip](https://github.com/biolab/orange3-timeseries/files/8160606/YearsInLineChart.zip)

**Comment by ajdapretnar** [comment]
Partially fixed in #220. The issue now is that the File reads the variable wrong (as seconds, not years). We should enable resetting the datetime format in Edit Domain.
