### ISSUE TITLE
The orange3-timeseries package is incompatible with scipy1.8.0

### ISSUE THREAD

**Issue by HannesLum** [biolab/orange3-timeseries#188]
##### Timeseries version
0.3.12 (in a development directory)

##### Orange version
3.31.1

##### Expected behavior
After setting up a new virtual environment with python3.8.12 and executing the following code in the command line (from the timeseries-directory)
```
pip install orange3==3.31.1
pip install -e .
python -m Orange.canvas
```
Orange should have opened itself with the timeseries-add-on successfully installed.

##### Actual behavior
Orange starts itself, but timeseries is nowhere to be found. Looking into the console-output reveals the reason:
```
Cannot import name '_centered' from 'scipy.signal.signaltools'
```
According to [this](https://stackoverflow.com/questions/71106940/cannot-import-name-centered-from-scipy-signal-signaltools) stackoverflow-question, the reason for this is that `_centered` is a private function and thus is not guaranteed to be there from one version of scipy to the next.

##### Additional info (worksheets, data, screenshots, ...)
Installing an earlier scipy-version will solve the problem:
```
pip install scipy==1.7.3
pip install orange3==3.31.1
pip install -e .
python -m Orange.canvas
```
But it might be a good idea to look into why the private function was imported in the first place for future versions of orange3 and if it could be replaced with something else.

**Comment by janezd** [comment]
Resolved in #178.
