### ISSUE TITLE
Hi I am facing an error with ARIMA and VAR models on Orange 3. Attached the issue screenshot. Any ideas?

### ISSUE THREAD

**Issue by Lann109** [biolab/orange3-timeseries#206]

**Comment by Lann109** [comment]
<img width="1072" alt="Screen Shot 2022-06-05 at 1 42 08 am" src="https://user-images.githubusercontent.com/106898805/172035355-5129759e-1c30-482c-8ae0-27819e4617c4.png">

**Comment by Lann109** [comment]
<img width="1496" alt="Screen Shot 2022-06-05 at 2 44 03 pm" src="https://user-images.githubusercontent.com/106898805/172035377-8c6ab539-f70f-4d75-accd-4edad1b80e94.png">

**Comment by janezd** [comment]
Oops, that's bad.

You didn't write the add-on version, but I assume it's 0.4, right?

@ajdapretnar, the changes I made to ARIMA require a release of Orange that includes https://github.com/biolab/orange-widget-base/pull/202. It was actually written in a comment, but we forgot about it. I'll revert #200 and then I'd ask you to create a new release 0.4.1. (Tomorrow).
