### ISSUE TITLE
Line Chart: show displayed attrs in saved image

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-timeseries#21]
Is there a chance to add attribute names to saved images from Line Chart? Now only a visualization is saved where the user has no idea what is displayed and which color is which attribute. Could be solved with a legend that would be useful in any case (perhaps below the chart)?

**Comment by ajdapretnar** [comment]
Current situation:
[r2_806_1.pdf](https://github.com/biolab/orange3-timeseries/files/1417661/r2_806_1.pdf)

**Comment by kernc** [comment]
Might be as simple as adding [`legend_enabled=True`](https://api.highcharts.com/highstock/legend.enabled).

**Comment by ajdapretnar** [comment]
Fixed via #90.
