### ISSUE TITLE
TIMESERIES add-on v0.4.0

### ISSUE THREAD

**Issue by LizzyOberholzer2** [biolab/orange3-timeseries#212]
**What's wrong?**

ORANGE DATA MINING
I installed the TIMESERIES add-on and it shows ticked, hence installed (restarted as well) but not showing up in my left pane.

**How can we reproduce the problem?** 

I think there is a bug with v0.4.0, install it and let me know if you can access the Timeseries widgets

**What's your environment?**

- Operating system: windows
- Orange version: 3.32
- How you installed Orange: from the official orange website

**Comment by Avicebron1972** [comment]
Thanks for the reply. One question: I would like to use Orange for my data science classes at the University of Venice (I think Orange is great for teaching), but I need to use ARIMA model for time series analysis. Are you planning to release a new version of ARIMA by the end of June or should I use another software?
Thanks. Regards :)

**Comment by ajdapretnar** [comment]
Timeseries release 0.4.1 is now available on PyPi and should be available on conda within a few hours.

**Comment by Avicebron1972** [comment]
Thanks! 👍
