### ISSUE TITLE
Periodogram: Use appropriate units for x-axis

### ISSUE THREAD

**Issue by mcapurso** [biolab/orange3-timeseries#214]

**Comment by mcapurso** [comment]
In Orange 3.32 , Timeseries 0.4.1 on x axis the numbers for periods are wrong.
If you get Yahoo finance widget, download Amazon quotes from October 2019 to June 2022 , open with line chart you see dates correctly. If you see correlogram , you see not dates but integer number of period. BUT if you open periodogram you see a strange VERY HIGH number on x axis. Probably the date is wrongly interpreted as a very high number. Please use period number or correct date.
![Screenshot from 2022-06-30 16-17-29](https://user-images.githubusercontent.com/8177173/176700755-c239ee94-d74b-406e-81b3-c2630c97844c.png)
![Screenshot from 2022-06-30 16-17-10](https://user-images.githubusercontent.com/8177173/176700760-fb791514-5a9a-48f3-8d6d-a3ab9010263d.png)
![Screenshot from 2022-06-30 16-16-35](https://user-images.githubusercontent.com/8177173/176700765-39f5f2ce-d541-43e8-a206-cad55efebf69.png)

**Comment by ajdapretnar** [comment]
Perhaps I have misunderstood the issue, but Periodogram does not show datetime on x axis. It shows periods.

**Comment by ajdapretnar** [comment]
A, right, I understand now. I was confused by the comparison with Line Chart. I agree the units should make more sense.
