### ISSUE TITLE
Line Chart: fix attribute selection on OSX

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-timeseries#22]
## Issue

This is so annoying, I can't stand it anymore.
On OSX, when selecting an attribute to display in a Line Chart, selection doesn't stop with a click. So when I move my mouse around, it is selecting all other attributes I happen to pass with the cursor. Extremely problematic for larger files (things get stuck).

Does not happen on Windows, so I reckon it's a Mac thing.

## Expected behaviour

When I click on an attribute, it is the only one selected, regardless of my mouse movement.
To select multiple attributes, only Shift and Ctrl/Cmd should work (or perhaps even click and drag, but that is optional).

I tried searching for a solution - no success so far.

**Comment by kernc** [comment]
I'll be ever indebted for any clues to a solution to this well-known problem.

**Comment by ajdapretnar** [comment]
I honestly can't even figure out the search term for this. 😒 
However, this doesn't happen in ListView in Select Columns or Box Plot or Distributions. Ok, in Box Plot and Distributions you can't select more than one instance, but in Select Columns, you can. So why don't I have any issues there? What is different about these two widgets? 😮 🤔

**Comment by kernc** [comment]
It's definitely a WebviewWidget (on WebEngine) issue. Only WebEngine widgets should be affected.

**Comment by ajdapretnar** [comment]
@NejcDebevec, @JakaKokosar perhaps describe your own tests of this: where it happens and where it doesn't.

**Comment by ajdapretnar** [comment]
#90 definitely doesn't fix this issue.

**Comment by janezd** [comment]
My bad, too. It should had been #21?

**Comment by ajdapretnar** [comment]
Yes, I think so. I will double check and close if so.

**Comment by janezd** [comment]
> Yes, I think so. I will double check and close if so.

@ajdapretnar, we're still waiting. 🙃

**Comment by ajdapretnar** [comment]
No longer happens.
```
PyQtWebEngine==5.15.5
PyQtWebEngine-Qt5==5.15.2

```
