### ISSUE TITLE
Line chart does not show VAR forecast

### ISSUE THREAD

**Issue by Alecampoy** [biolab/orange3-timeseries#223]
##### Timeseries version

0.4.1

##### Orange version

3.32.0 on windows

##### Expected behavior
To plot the forecast in the line chart widget

##### Actual behavior
Forecast is not represented. I belive the problem comes from the Date format of the VAR's output, that has scientific notation instead of date format.

##### Steps to reproduce the behavior
A simple forecast, like the one in the help website shows the behaviour (screenshoot attached)

##### Additional info (worksheets, data, screenshots, ...)

![imagen](https://user-images.githubusercontent.com/79199360/181733463-6b93e770-5be8-4ad4-88a6-783333c347b3.png)

**Comment by ajdapretnar** [comment]
I am quite sure it shows the prediction, you just have too much data to see it in the Line Chart. Increase forecast step if you wish to see more of the forecast.

**Comment by Alecampoy** [comment]
I tried that already, but no way it shows the confidence intervals
![imagen](https://user-images.githubusercontent.com/79199360/182181371-fe67f9eb-ef7f-41db-802c-8c167d545a7b.png)

**Comment by ajdapretnar** [comment]
My bad, it indeed does not show confidence intervals. Will be fixed in #220.

**Comment by ajdapretnar** [comment]
Fixed via #220.
