### ISSUE TITLE
Unable to get rid of deprecated Aggregate widget

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3-timeseries#245]
##### Timeseries version
0.5.1

##### Orange version
3.33

##### Expected behavior
When installing any version of Timeseries that was released after the Aggregate widget has been deprecated, Aggregate should disappear from the widgets list, and instances of Aggregate in workflows should be replaced by Moving Transform at opening.

##### Actual behavior
On my Mac (OS 13.0.1 on Silicon) Aggregate is still there, in the widget catalog _and_ in old workflows that I open

##### Steps to reproduce the behavior
I have no idea

##### Additional info (worksheets, data, screenshots, ...)
Let me know if there's anything I can provide

**Comment by janezd** [comment]
I suppose you can remove it manually by deleting /Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.8/site-packages/orangecontrib/geo/widgets/owaggregate.py. Or, just to be safe, first just move the file to another location.

This is of course not a solution. @markotoplak, @PrimozGodec, @ales-erjavec, any ideas why a widget that was removed in the new version of an add-on is not removed from directory?

**Comment by markotoplak** [comment]
@wvdvegte, could you please add a Python Script widget and run this snippet:

```
from orangecanvas.registry import cache
c = cache.registry_cache()
print(c.keys())
```

Could you share the output with us so that we'll know where widgets are stored on your computer? Please share at least the parts corresponding to widgets from the timeseries add-on.

**Comment by wvdvegte** [comment]
> Could you share the output with us

Here you go:

'/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/_owmodel.py'
'/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/_rangeslider.py'
'/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/owaggregate.py'
'/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/owarimamodel.py'
'/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/owcorrelogram.py'
'/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/owdifference.py'
'/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/owgrangercausality.py'
'/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/owinterpolate.py'
'/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/owlinechart.py'
'/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/owmodelevaluation.py'
'/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/owmovingtransform.py'
'/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/owperiodbase.py'
'/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/owperiodogram.py'
'/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/owseasonaladjustment.py'
'/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/owspiralogram.py'
'/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/owtabletotimeseries.py'
'/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/owtimeslice.py'
'/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/owvarmodel.py'
'/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/orangecontrib/timeseries/widgets/owyahoofinance.py'

**Comment by ales-erjavec** [comment]
```bash
$ unzip -l Orange3_Timeseries-0.5.1-py3-none-any.whl | grep owaggregate                                                        
     8383  2022-06-03 11:39   orangecontrib/timeseries/widgets/owaggregate.py
     3524  2022-06-01 08:36   orangecontrib/timeseries/widgets/tests/test_owaggregate.py
```
Note:  make sure to run `python setup.py clean --all` before doing a release.

**Comment by janezd** [comment]
@ales-erjavec, thanks.

I updated https://github.com/biolab/orange3/wiki/Preparing-an-Add-on-release, and prepared a hopefully correct new release.

**Comment by wvdvegte** [comment]
Right! The Aggregate widget has finally gone!
