### ISSUE TITLE
Line chart pop-up menu not documented

### ISSUE THREAD

**Issue by kaimikael** [biolab/orange3-timeseries#248]
##### Timeseries version

0.5.1

##### Orange version

3.34.0

##### Expected behavior
In the Line chart widget one can right-click on the display to bring up a pop-up menu with lots of options.  
I expected to be able to find an explanation of how it works in the documentation.

##### Actual behavior
This menu is not documented in https://orangedatamining.com/widget-catalog/time-series/line_chart/.
A problem with this is for example trying to adjust the x-axis (see attached screenshots).  It seems the values that one enters for (presumably) the min and max values are something like seconds since the epoch, which is somewhat cumbersome to use.  I tried entering dates like “1980-01-01”, but these don’t seem to be understood, so it would be nice with an explanation of how to use them.

##### Steps to reproduce the behavior
Create a Line Chart widget with input.  Right-click on the display, a pop-up menu appears.  Press the “?” icon of the widget, the help page contains nothing about the pop-up menu.

##### Additional info (worksheets, data, screenshots, ...)

<img width="926" alt="Screenshot 2022-12-15 at 16 11 33" src="https://user-images.githubusercontent.com/10616212/207899700-a0f1dabe-5f67-4a04-86a2-e5bae02b51e8.png">
<img width="924" alt="Screenshot 2022-12-15 at 16 12 42" src="https://user-images.githubusercontent.com/10616212/207899714-62141516-437e-4341-bf3a-800c9c6f84f7.png">

**Comment by ajdapretnar** [comment]
I added a short note in the documentation. However, these are standard pyqtgraph options, so please refer to their own [documentation](https://pyqtgraph.readthedocs.io/en/latest/user_guide/mouse_interaction.html).

**Comment by kaimikael** [comment]
Well, I as a user don’t necessarily know, or for that matter care, what particular graphics library is being used, so that I can go search for what happens to be the standard behaviour of that package :-p 
I had at look at https://orangedatamining.com/widget-catalog/time-series/line_chart/, but I guess the note in the documentation hasn’t found it’s way to the web page yet.

Still, I think the min/max values of the x axis are a bit cumbersome to use, if they actually are given as seconds.

**Comment by janezd** [comment]
I see no non-intrusive way to inform the user about right-clicking. (Nobody particularly likes the popup hints that appear in some widgets, so we avoid them). Perhaps we could add a button that would open the same pop-up as one gets by right-clicking?

As for time in seconds: this is handled by pyqygraph. Pyqtgraph is by far the best option for plotting data in our context (we know, we used quite a few), but it can make breaking changes from version to version. I think I know how we could perhaps force it to maybe accept a different input (including parsing dates), but I'm pretty sure this would break in one of the future versions. We should probably add a different way to set the time range.

**Comment by kaimikael** [comment]
Oh, I don’t require an interactive help for the context menu—I’m perfectly happy with the options being described on the documentation web page.  I’d even be happy with just a link to the relevant pyqtgraph documentation, as long as I don’t have to read the source code to figure out how things work :-)

Very annoying with non-backwards-compatible updates, I feel for you.
