### ISSUE TITLE
Unable to install Timeseries add-on: command failed

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3-timeseries#261]
**What's wrong?**
My colleague is trying to install the Timeseries add-on trough Options -> Add-ons. During installation (after selecting the add-on and clicking OK), error messages appear:
Short error message:
`Command failed: python python -m pip install --upgrade --upgrade-strategy=only-if-needed Orange3-Timeseries==0.6.0 exited with non zero status.`

Long error message:
[Timeseries install error.txt](https://github.com/biolab/orange3/files/13439408/Timeseries.install.error.txt)
The problem does not occur with other add-ons

**How can we reproduce the problem?** 
I don't know. I have a Mac with a different processor (M1, not M1 Pro), and have a slightly older OS version (14.1, not 14.4.1) and had no problems installing the add-on

**What's your environment?**

- Operating system: Mac OS 14.1.1
- Orange version: 3.36.2
- How you installed Orange: 3.35 from DMG, updated through Options menu.

**Comment by kraaidelft** [comment]
>   brew install automake libtool
>   /Applications/Orange.app/Contents/MacOS/pip install cython
>   ```

Doesn't work, I get a:
Error: Git must be installed and in your PATH!
/usr/local/Homebrew/Library/Homebrew/version.rb:368:in `initialize': Version value must be a string; got a NilClass () (TypeError)

**Comment by PrimozGodec** [comment]
So, the current state: 
- I am helping lxml to improve their wheel-building system: https://github.com/lxml/lxml/pull/388; when it is finished, they will also provide MacOS ARM wheels
- Since it can take some time to be finished, I propose skipping installing yfinace and pandas_datasets on MacOS that require lxml library for now. #262 It will only affect the Yahoo widget.

**Comment by PrimozGodec** [comment]
We merged the temporary solution from #262 and made a release. Now, orange3-timeseries should install successfully. It will lack the Yahoo finance widget on MacOS. We are working towards getting this widget back as soon as possible by helping lxml maintainer to provide wheels.

**Comment by PrimozGodec** [comment]
We re-added the Yahoo widget for Mac users. :) Please update your orang3-timeseries version to 0.6.2 in add-on dialog.
