### ISSUE TITLE
Aggregate: fix datetime handling

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-timeseries#36]
##### Timeseries version

0.3.2

##### Orange version

3.8.dev

##### Expected behavior
Aggregate by day aggregates from 00:00 to 23:59 of each day in the data set.

##### Actual behavior
Aggregation is incorrect - it considers instances from 2 hours before midnight until 22:00 of the wanted day. Potentially a timezone issue.

##### Steps to reproduce the behavior
File (set Example as continuous) - As Timeseries - Aggregate (by day, sum) - Data Table.

##### Additional info (worksheets, data, screenshots, ...)
https://docs.google.com/spreadsheets/d/1wblEsHSfCFGBKZmG-fDaiFNBLDK7cTGKKKAzH3xiO6E/edit?usp=sharing

Expected:

| Date | Example |
|---|---|
| 2017-11-11 | 3 |
| 2017-11-12 | 2 |
| 2017-11-13 | 4 |

Acutal:

| Date | Example |
|---|---|
| 2017-11-10 | 2 |
| 2017-11-11 | 2 |
| 2017-11-12 | 5 |
| 2017-11-13 | 0 |

**Comment by nadirsidi** [comment]
I'm seeing the same issue with loading timezone-naive ISO timestamps at the 15-minute level and then trying to aggregate to daily. It appears to perhaps assume my local timezone, then I get the daily timestamps for 5am to 5am.

**Comment by wvdvegte** [comment]
I noticed that Aggregate actually converts all timestamps to GMT, assuming that they refer to the time zone setting of the computer on which Orange is running. Timestamps during summer time get one hour extra subtracted, which is very confusing.
IMO this should at least be documented, but it would be better if conversion to GMT could be just an option - and not the default.
