### ISSUE TITLE
Line Chart: show instance count

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-timeseries#52]
##### Timeseries version

0.3.2

##### Orange version

3.10.dev

##### Expected behavior
One can see and inspect occurrences of a phenomenon in Line Chart.

##### Actual behavior
It is nearly impossible to see how many instances occurred in a certain time frame.

##### Additional info (worksheets, data, screenshots, ...)
Often one would like to see, for example, _when_ a certain phenomenon took place. This is very very difficult with Timeseries.
One option is to add 1 to each instance with Feature Constructor, use Aggregate, but still Line Chart optimizes projection and one won't see 'missing data'/absence of a phenomenon.

1. Add option to Line Chart to see an unoptimized plot (with equal width dates).
2. Have Line Chart perhaps show instance count as a default (upon opening it).

In the image below, for example, I want to see that there were no occurrences on the 21st of January. One does not notice this due to optimization.
![image](https://user-images.githubusercontent.com/12524972/35799971-c8a1d87a-0a67-11e8-8779-46f444d294d4.png)

**Comment by ajdapretnar** [comment]
Please, please, please. 🙏 I really need this for my analysis!

**Comment by kernc** [comment]
See if it looks ok if you pass it [`xAxis_ordinal=False`](https://api.highcharts.com/highstock/xAxis.ordinal).

**Comment by ajdapretnar** [comment]
After some troubles I've managed to set this up.

However, @lanzagar pointed out this is a different kind of a problem. Do I understand correctly that Line Chart only plots data points as they are. The main part is done in As Timeseries that transforms sequences in datetime. So if there is no entry for, say, 2018-02-14, this day will never get plotted in Line Chart... Should As Timeseries (or some other widget) add missing dates with 0 or NaN as an entry? 🤔 How would one see phenomenons that are recorded only once in a while? For Text analysis for example?

**Comment by kernc** [comment]
> Do I understand correctly that Line Chart only plots data points as they are. 

I don't see how this is unexpected or a problem. Would you prefer it plotted data points _not_ as they are? 😆 

If there is no data at a particular point in time, it is _just not there_. A constant frequency if a very vague and limiting assumption. `xAxis_ordinal=True` still might work, but if you need all data points on some interval constantly-spaced, why not make them so. You can do it in pandas:
```py
df = df.resample('D').mean().fillna(0)
```
Supposing you already have daily values, it will keep them, filling in the missing days with zeros.

Supposing this fits in Orange, I guess _Aggregate_ widget comes closest to resampling, with _daily_ aggregation potentially adequate to filling in missing dates (optionally, on a checked checkbox). Or indeed maybe _As Timeseries_, optionally, on a checkbox.

**Comment by kernc** [comment]
@ajdapretnar Resolution?

**Comment by ajdapretnar** [comment]
Super high. 3840 x 2160

**Comment by kernc** [comment]
This is not a joking venue.

**Comment by ajdapretnar** [comment]
Why would it be?

Resolution: my requests fall outside the scope of what anyone is willing to implement here. I will do with manual preprocessing in pandas.
