### ISSUE TITLE
Line Chart: Add plot overlaps

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-timeseries#53]
##### Timeseries version

0.3.3

##### Orange version

3.10.dev

##### Expected behavior
Add plot displays plot below the existing one.

##### Actual behavior
Plots overlap.

##### Steps to reproduce the behavior
Plot two variables in the same graph with Add plot.

##### Additional info (worksheets, data, screenshots, ...)
<img width="1563" alt="screen shot 2018-02-26 at 15 04 28" src="https://user-images.githubusercontent.com/12524972/36674960-ed207066-1b07-11e8-89a1-5c4705f6e9cd.png">

**Comment by kaelte** [comment]
Same behaviour on newer version:
```
Mac OS X 10.14.4
Orange 3.20.1
Timeseries 0.3.3
```

**Comment by ajdapretnar** [comment]
Fixed via #87.
