### ISSUE TITLE
Line chart pan and zoom

### ISSUE THREAD

**Issue by readmodifywrite** [biolab/orange3-timeseries#56]
##### Timeseries version

0.3.3

##### Orange version

3.11.0

##### Expected behavior
Older versions allowed panning and zooming

##### Actual behavior
The UI for pan and zoom appears to have been removed

##### Steps to reproduce the behavior
Use line charts in latest version.

**Comment by lippjd** [comment]
Also experiencing this issue - zoom/pan section under main plot is completely missing. Any resolutions or workarounds available?

**Comment by ajdapretnar** [comment]
This is not an issue. Zoom and pan were purposefully removed a while ago. I do not remember the reason, but I think the functionality wasn't implemented the way it was supposed to.

**Comment by ninadpchaudhari** [comment]
Until this is fixed, the workaround that worked for me was to freeze the orange3-timeseries package to 0.3.1
https://pypi.org/project/Orange3-Timeseries/0.3.1/ 

My Current Orange3 version  : 3.26 

I can confirm that zoom & pan works on that version.

**Comment by janezd** [comment]
@ajdapretnar, if we don't remember the reason and there seem to be none, we can reenable it, right?

If this is a highcharts issue, though, we can just close this, as it will be fixed as a part of #58.

**Comment by ajdapretnar** [comment]
I cannot find the original PR due to some rearranging of repositories. If I remember correctly, this was removed because it didn't work well. Sure, we can bring it back, but since we cannot revert a PR that undid this, I don't think it's realistic to expect we will be able to do it on our own. So my vote is for #58.
