### ISSUE TITLE
Replace Highcharts with fully open-source charting library

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-timeseries#58]
##### Timeseries version

0.3.3

##### Orange version

3.14.0

##### Idea
Replace Highcharts with a fully OS alternative. A large discussion was opened in https://github.com/biolab/orange3/issues/2044. Check it for ideas.

**Comment by msat-cont** [comment]
One more vote for having this add-on (re)implemented with commercial-friendly libraries.

**Comment by leeoniya** [comment]
@ajdapretnar

shameless plug for something that may work for you: https://github.com/leeoniya/uPlot

**Comment by ajdapretnar** [comment]
@leeoniya Thanks! We will have a look, but probably we'll try implementing it in Qt first.

**Comment by ajdapretnar** [comment]
@janezd This is done, if I'm not mistaken?
