### ISSUE TITLE
Orange3-Timeseries does not install (Windows 10)

### ISSUE THREAD

**Issue by CornelisRemmert** [biolab/orange3-timeseries#6]
Timeseries does not install.
Orange3.3.8 Windows10. 
Two remarks on failing to create wheel (for Orange3-Timeries and for statsmodels).
And at the end:

![image](https://cloud.githubusercontent.com/assets/20670746/21586653/940d1116-d0d3-11e6-9e52-1c36d1e0158e.png)

**Comment by ajdapretnar** [comment]
Yes, it's a problem. You need to manually install statsmodels package.
Go to [this site](http://www.lfd.uci.edu/~gohlke/pythonlibs/#statsmodels) and download the statsmodels wheels. You need a proper package for your OS, e.g. if you are running Python 3.4 on a 64-bit machine, then download statsmodels‑0.6.1‑**cp34**‑none‑win_**amd64**.whl.

In the console, find the directory where the .whl file is (probably Downloads). Then do:
`pip install statsmodels‑0.6.1‑cp34‑none‑win_amd64.whl`

This should manually install statsmodels. Then Timeseries should install as well (repeat pip install orange3-timeseries).

**Comment by CornelisRemmert** [comment]
thanks, this worked

**Comment by CornelisRemmert** [comment]
Although, I do not see line chart

**Comment by kernc** [comment]
Please open a separate bug report for this to be discussed there. Thanks.
