### ISSUE TITLE
Compare labeled data in Line Chart

### ISSUE THREAD

**Issue by gslopez** [biolab/orange3-timeseries#60]
Hi, i have the following problem.

My database looks like this:

| Name  | Date  |  Value  |
|---|---|---|
|  Region A | 01/01/2011  | 1  |
|  Region A | 02/01/2011  | 5  |
|  Region A | 03/01/2011  | 10  |
|  Region B | 01/01/2011  | 15  |
|  Region B | 02/01/2011  | 50  |
|  Region B | 03/01/2011  | 2  |

I want to compare Region A and Region B charts, but Orange shows all data grouped in one single chart.
Is it possible ?

Thank you !

**Comment by kernc** [comment]
It's possible with a workflow like this:
![screenshot_2018-10-26_04-26-36](https://user-images.githubusercontent.com/684364/47540952-a4d83080-d8d7-11e8-9e8e-3a124a88e8ad.png)

In Select Rows, you select the rows matching RegionA. The you drag Matching Data into Edit Domain, where you rename the column Value to ValueA. Then you merge the two data sets on Date. You will end up with data containing columns ValueA and Value (B) you can plot in Line Chart.
