### ISSUE TITLE
Incompatible scipy 1.3.0 and statsmodels 0.9

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-timeseries#62]
Due to incompatibility of scipy 1.3.0 and statsmodels 0.9, the Timeseries add-on fails to import if the wrong two versions are installed.

https://github.com/statsmodels/statsmodels/issues/5759

This is just a reminder to fix the statsmodels version once they make a release, which is due in June. The instant workaround:
```

pip install --upgrade Cython
pip install --upgrade git+https://github.com/statsmodels/statsmodels
```

**Comment by PrimozGodec** [comment]
Prerelease is already available but there is no release yet https://github.com/statsmodels/statsmodels/issues/5845. Hope it happens soon.

**Comment by ajdapretnar** [comment]
I think it's out: https://pypi.org/project/statsmodels/#history

**Comment by PrimozGodec** [comment]
Yep, it is. :) #66 sets new version limit
