### ISSUE TITLE
Seasonal Adjustment error

### ISSUE THREAD

**Issue by Norsusan** [biolab/orange3-timeseries#76]
![image](https://user-images.githubusercontent.com/29728592/74430903-cc843c80-4e2b-11ea-84d0-9486eef503e8.png)

I receive this error when trying to set Seasonal Adjustment to 12 for Air Passenger dataset.

![image](https://user-images.githubusercontent.com/29728592/74431033-26850200-4e2c-11ea-9efb-15f9a484277f.png)

![image](https://user-images.githubusercontent.com/29728592/74484145-0aae4a00-4e86-11ea-90eb-fec29f9a5cb2.png)

**Comment by ajdapretnar** [comment]
Should be fixed with the latest release. It's already on PyPi and I am almost done preparing a build for conda. Should be out soon.

**Comment by Norsusan** [comment]
Thank you,

 

Norm

 

Norman Abraham CFP

 

Tel: (613) 261-0947

Email:  <mailto:norman.abraham@teksavv.com> norman.abraham@teksavv.com

              <mailto:risk.analytics@teksavvy.com> risk.analytics@teksavvy.com

Web:   <http://www.RiskAnalytics@teksavvy.com> www.RiskAnalytics@teksavvy.com

 

“THINK OUTSIDE THE BOX”

**Comment by ajdapretnar** [comment]
Unfortunately the new release doesn't solve the issue. New PR is coming with the proper fix.

**Comment by anamilkochar** [comment]
hi, i am also facing the same error on running seasonal adjustment widget. when will the same be fixed?

**Comment by Norsusan** [comment]
I believe the fix will be on the next revision.

**Comment by ajdapretnar** [comment]
I am working on it. I was busy writing my PhD, hence the delay. Just pushed the latest release on PyPi, but the service seems to be down atm. Should be out today or tomorrow, I hope. 🤞
