### ISSUE TITLE
Line Chart Crashes

### ISSUE THREAD

**Issue by RoboDoig** [biolab/orange3-timeseries#8]
Line chart crashes as soon as widget is dragged into Orange canvas

**Exception: AttributeError: 'PlotConfigWidget' object has no attribute 'controlled_attributes'**
Module:
Orange.widgets.gui:158
Widget Name:
Line Chart
Widget Module:
orangecontrib.timeseries.widgets.owlinechart:348
Widget Scheme:
/tmp/ows-dcfw_s0t.ows.xml
Version:
3.3.12
Environment:
Python 3.6.0 on Linux 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64
Installed Packages:
AnyQt==0.0.8, Bottleneck==1.2.0, Genesis-PyAPI==1.2.0, Orange-Bioinformatics==2.6.20, Orange3-Timeseries==0.2.6, Orange3==3.3.12, SecretStorage==2.3.1, cffi==1.9.1, chardet==2.3.0, conda==4.2.13, cryptography==1.7.1, dill==0.2.6, docutils==0.13.1, idna==2.2, joblib==0.10.3, keyring==10.3, keyrings.alt==2.0, numpy==1.12.0, pandas==0.19.2, patsy==0.4.1, pip==9.0.1, pyOpenSSL==16.2.0, pyasn1==0.1.9, pycosat==0.6.1, pycparser==2.17, pyqtgraph==0.10.0, python-dateutil==2.6.0, pytz==2016.10, requests-cache==0.4.13, requests==2.12.4, scikit-learn==0.18.1, scipy==0.18.1, serverfiles==0.2, setuptools==27.2.0, six==1.10.0, slumber==0.7.1, statsmodels==0.8.0, wheel==0.29.0, xlrd==1.0.0
Machine ID:
203178706247068
**Stack Trace:**
Traceback (most recent call last):
  File "/home/erskina/miniconda3/lib/python3.6/site-packages/orangecontrib/timeseries/widgets/owlinechart.py", line 348, in add_plot
    config = PlotConfigWidget(self, ax, self.varmodel)
  File "/home/erskina/miniconda3/lib/python3.6/site-packages/orangecontrib/timeseries/widgets/owlinechart.py", line 46, in __init__
    callback=lambda: self.sigType.emit(ax, self.plot_type))
  File "/home/erskina/miniconda3/lib/python3.6/site-packages/Orange/widgets/gui.py", line 1648, in comboBox
    ValueCallbackCombo(master, value, valueType, emptyString))
  File "/home/erskina/miniconda3/lib/python3.6/site-packages/Orange/widgets/gui.py", line 2127, in connectControl
    master.connect_control(value, cfront)
  File "/home/erskina/miniconda3/lib/python3.6/site-packages/Orange/widgets/gui.py", line 158, in connect_control
    self.controlled_attributes[name].append(func)
AttributeError: 'PlotConfigWidget' object has no attribute 'controlled_attributes'

**Local Variables:**
OrderedDict([('func',
              <Orange.widgets.gui.CallFrontComboBox object at 0x7fb37a455c50>),
             ('name', 'plot_type'),
             ('self',
              <orangecontrib.timeseries.widgets.owlinechart.PlotConfigWidget object at 0x7fb37a44f438>)])

**Comment by kernc** [comment]
If you are willing to test the git version, I just pushed https://github.com/biolab/orange3-timeseries/commit/06632220ac7c56eaf54c4ddd17cf515fb1b84804 which may fix it. Thanks.

**Comment by RoboDoig** [comment]
Just tested, works great now, thanks!
