### ISSUE TITLE
Y Axis Scales and Graph Mix

### ISSUE THREAD

**Issue by Norsusan** [biolab/orange3-timeseries#83]
ails in the
sections below.
-->

##### Timeseries version
0.3.5

##### Orange version
3.24.1

##### Expected behavior

![Expected Behavior](https://user-images.githubusercontent.com/29728592/77820153-748d5680-70b6-11ea-9285-ac84e8cffa33.jpg)

##### Actual behavior

![What I Get](https://user-images.githubusercontent.com/29728592/77820154-79eaa100-70b6-11ea-8976-e3a885249750.jpg)

##### Steps to reproduce the behavior
Using Air Passenger data and Seasonal Adjustment workflow example

**Comment by ajdapretnar** [comment]
The overlap has been fixed in #87.
