### ISSUE TITLE
With or without an As Timeseries widget, the transformation to timeseries should behave the same way

### ISSUE THREAD

**Issue by irgolic** [biolab/orange3-timeseries#85]
Connecting a Data output to a Time series input is allowed, but just shows a horizontal line.

Time series widgets should infer that 'As Timeseries' was supposed to be added in between, and try to use the first datetime feature as the sequential attribute, or instance ordering if there's no datetime feature.

**Comment by kernc** [comment]
> Time series widgets should infer that 'As Timeseries' was supposed to be added in between, 

This [is the case](https://github.com/biolab/orange3-timeseries/search?q=%22def+set_data%22+%22Timeseries.from_data_table%28data%29%22&unscoped_q=%22def+set_data%22+%22Timeseries.from_data_table%28data%29%22).

> and try to use the first datetime feature as the sequential attribute

This [is the case](https://github.com/biolab/orange3-timeseries/blob/b987e1ab4322e0ad4320b6881beb30bdc03c93f4/orangecontrib/timeseries/timeseries.py#L22-L27).

> or instance ordering if there's no datetime feature.

And this is not (yet).

IIRC, the widget is there exactly to make the choice of the temporal attribute convenient and _explicit_.

**Comment by ajdapretnar** [comment]
I think it is necessary if there is more than one time variable or there is an non-explicit continuous variable with 'pseudotime'.

**Comment by irgolic** [comment]
Ah, I should've opened with the use case.

[My dataset](https://drive.google.com/open?id=1n5oN0C8n5HJcWgkY4i1ONhDiQ66emzGe) contains a couple of different sources merged together, so the timestamps are a bit jumbled. It seems the time delta isn't detected properly if I plug Data directly into a timeseries widget, but it works fine if I run it through As Timeseries.

**Comment by kernc** [comment]
Yeah, in addition, the widget _sorts_:
https://github.com/biolab/orange3-timeseries/blob/49d864820d05cb9011494bdf3f9691cf6c701ba9/orangecontrib/timeseries/widgets/owtabletotimeseries.py#L114-L116

**Comment by irgolic** [comment]
I see. Plugging in what I did probably isn't too meaningful anyway, more than anything else, I was just confused as to why it was acting differently. It'd be nice if it sorted without As Timeseries too.

**Comment by ajdapretnar** [comment]
@irgolic Perhaps rename the issue?

**Comment by irgolic** [comment]
Related: NaNs should be ignored when Data is converted to Timeseries, and in As Timeseries, a warning should be thrown instead of an error upon NaNs.

Ideally, a warning should be shown in any Timeseries widget if there's NaN values present in the time variable. What's the easiest way of implementing this across the add-on, without duplicating Warning code in each widget?

**Comment by ajdapretnar** [comment]
Fixed via #95.
