### ISSUE TITLE
Moving Transform: fix PyTable

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-timeseries#88]
Moving Transform has several issues.

1. It starts with a table with 3 redundant columns (4, 5, 6).

2. Try to sort by Aggregation function. Then Add Transform. Widget crashes with:
`File "/Users/ajda/orange/orange3-timeseries/orangecontrib/timeseries/widgets/owmovingtransform.py", line 169, in on_add_transform    self.table_model.append([self.var_model[0], self.last_win_width, AGG_FUNCTIONS[0]])  File "/Users/ajda/orange/orange3/Orange/widgets/utils/itemmodels.py", line 331, in append    self.extend([row])  File "/Users/ajda/orange/orange3/Orange/widgets/utils/itemmodels.py", line 342, in extend    self[i:] = rows  File "/Users/ajda/orange/orange3/Orange/widgets/utils/itemmodels.py", line 279, in __setitem__    self._check_sort_order()  File "/Users/ajda/orange/orange3/Orange/widgets/utils/itemmodels.py", line 309, in _check_sort_order    raise RuntimeError("Can't modify PyTableModel when it's sorted")RuntimeError: Can't modify PyTableModel when it's sorted`

Occasionally, Python also segfaults. Anyhow, widget is then caught in an infinite loop of errors.

3. Widget could be 'Orangized' a bit. Double-clicking to edit is not implemented in other Orange widgets. I would prefer to solve this similar to Select Rows. And not have the table sortable.

**Comment by janezd** [comment]
After the latest changes, it misbehaves differently.

I would reorganize the widget to have:

- a combo to select the aggregation (the same for all variables)
- a spin to set the window width (again the same for all)
- a check box for "non-overlapping windows" (like now)
- some control for selection of attributes. It can be a list view with multiple selection or a one-column table with variable names and checkboxes + checkbox for (de)selecting all. And a filter to rule them all.
